### ISSUE TITLE
Suggestion: Make Templates Available for Editing

### ISSUE THREAD

**Issue by aorin1** [TheGrizzMD/coinops-es-de#2]
Hi! Do you have the PSD templates so the user can edit the backgrounds and possibly add different TV sets, remove the action figures and so on from the theme?
This is also useful for adding new systems that aren't currently supported, and variations too.
Thanks!

**Comment by TheGrizzMD** [comment]
I put all of that stuff in this repo:
https://github.com/TheGrizzMD/coinops-es-de-assets

There are no PSD files, but you can open the xcf files in GIMP and then export them to PSD if you want to use photoshop.

**Comment by aorin1** [comment]
Thanks!
