### ISSUE TITLE
missing text

### ISSUE THREAD

**Issue by B-Nerd** [TheGrizzMD/coinops-es-de#8]
the theme on the pc arcade systems has "missing text" because above the tv the piece of paper is black & the pc part of pc arcade is also black the pc part is missing like you can see here
![Screenshot_20240414_195323](https://github.com/TheGrizzMD/coinops-es-de/assets/65131530/cac600d2-37e2-4b35-ab12-7a87dcf484dc)
![Screenshot_20240414_195615](https://github.com/TheGrizzMD/coinops-es-de/assets/65131530/1796d28f-b31b-45e5-8ce8-538d856ab887)
& as you can pc the part is not broken just not visible on a black background

**Comment by TheGrizzMD** [comment]
Thanks, that logo needs an outline like the Atari ST one next to it in your second screenshot. If you know how to create that you can submit it and if not I can try to make one myself to replace the current image so that it is visible in the game list.

**Comment by B-Nerd** [comment]
> Thanks, that logo needs an outline like the Atari ST one next to it in your second screenshot. If you know how to create that you can submit it and if not I can try to make one myself to replace the current image so that it is visible in the game list.

sadly i don't know how to do that i wish i could

**Comment by TheGrizzMD** [comment]
I added an outline to the logo so it should be visible now. 
![image](https://github.com/TheGrizzMD/coinops-es-de/assets/39314057/f9a12c02-ec00-4f80-bc09-d95f1a7fe7a4)
